runtime: python38

entrypoint: gunicorn -b :$PORT gitreadybackend.wsgi:application

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: 'gitreadybackend.settings'

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto

runtime_config:
  python_version: 3

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 3
  min_pending_latency: 30ms
  max_pending_latency: automatic
