import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react';
import { Modal, Menu, Container, Dropdown, Button, Input, TextArea } from 'semantic-ui-react';
import Link from 'next/link';
import navbarStyles from '../styles/Navbar.module.css';
import dynamic from 'next/dynamic';




//whenever text changes, log it

//import VoiceRecorder from '@/components/VoiceRecorder'
const DynamicVoiceRecorder = dynamic(() => import('@/components/RecordingComponent'), { ssr: false });
export default function Home() {
const [text, setText] = useState("");
const [modalIsOpen, setModalIsOpen] = useState(false);

const handleTextChange = (event) => {
  setText(event.target.value);
};

const handleModalClose = () => {
  console.log('Modal closed');
  // SEND PERSONALITY DESCRIPTION TO BACKEND
};

useEffect(() => {
  console.log(text);
}, [text]);

  return (
    <>
      <Head>;
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Menu fixed="top" inverted>
  <Container className={navbarStyles.menuContainer} style={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
    <Menu.Item as="a" header href="https://nextjs.org" className={navbarStyles.menuItem}>
      <h1 className={styles.title}>Welcome to U-BOT!</h1>
    </Menu.Item>
    {/* <Menu.Item className={navbarStyles.menuItem}>
      <p>Please select your voice</p>
    </Menu.Item> */}
    <Menu.Item className={navbarStyles.menuItem}>
      <Dropdown
        placeholder="Select a voice"
        selection
        options={[
          { key: 'bella', value: 'Bella', text: 'Bella' },
          { key: 'arnold', value: 'Arnold', text: 'Arnold' },
        ]} 
        style={{display: 'flex', justifyContent: 'center', alignItems: 'center'}}
      />
    </Menu.Item>
    <Modal
      closeIcon onClick={() => setModalIsOpen(true)} isOpen={modalIsOpen} onRequestClose={() => setModalIsOpen(false)} onClose={handleModalClose}
      trigger={<Button secondary className={navbarStyles.menuItem} style={{ maxWidth: '300px', width: '100%', fontSize: '24px'  }}>Edit Personality</Button>}
    >
      <Modal.Header>Personality Description</Modal.Header>
      <Modal.Content>
        <TextArea placeholder="Enter your text" rows={10} style={{ width: '100%' }}  value={text}
          onChange={handleTextChange}/>
      </Modal.Content>
    </Modal>
  </Container>
</Menu>


        <h1>Voice Recorder</h1>
        <DynamicVoiceRecorder />
        
      </main>
    </>
  )
}
